### ISSUE TITLE
GitHub Branding

### ISSUE THREAD

**Issue by jsoref** [seanghay/insomnia-plugin-github-light-theme#3]
https://github.com/logos

### Please don’t do these things
❌ Use the Octocat or GitHub logo for your application’s icon
❌ Create a modified version of the Octocat or GitHub logo
❌ Integrate the Octocat or GitHub logo into your logo
❌ Use any GitHub artwork without permission
❌ Sell any GitHub artwork without permission
❌ Change the colors, dimensions or add your own text/images

###

Note: GitHub should be written as such, not as `Github` [sic]

@github

**Comment by seanghay** [comment]
> https://github.com/logos
> 
> ### Please don’t do these things
> ❌ Use the Octocat or GitHub logo for your application’s icon
> ❌ Create a modified version of the Octocat or GitHub logo
> ❌ Integrate the Octocat or GitHub logo into your logo
> ❌ Use any GitHub artwork without permission
> ❌ Sell any GitHub artwork without permission
> ❌ Change the colors, dimensions or add your own text/images
> 
> Note: GitHub should be written as such, not as `Github` [sic]
> 
> @github

Are you having OCD? Lol

**Comment by seanghay** [comment]
I just released another theme. Maybe you need to check that out as well. https://github.com/seanghay/insomnia-plugin-github-dark-theme
